### ISSUE TITLE
Have to curl every time I plug it in

### ISSUE THREAD

**Issue by ZachSaucier** [gholker/led-backlight-cmstorm#4]
Thanks for this, it works great! 

How do I prevent the need for having to run the curl script this every time that I plug my keyboard in?

**Comment by ZachSaucier** [comment]
I found it under my user -> Applications folder. So I can just run that file without having to open up the terminal and download it every time.

**Comment by gholker** [comment]
Glad it helps :) @ZachSaucier 

I did some updates this weekend to make it work for latest Mac OS and so that it's configurable. Seems not all keyboards matched my own.
